# Generated by Django 4.2.4 on 2023-09-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='product',
        ),
        migrations.AddField(
            model_name='version',
            name='product',
            field=models.ManyToManyField(to='catalog.product', verbose_name='продукт'),
        ),
    ]
