# Generated by Django 4.2.4 on 2023-10-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options_alter_product_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ManyToManyField(related_name='version', to='catalog.product', verbose_name='продукт'),
        ),
    ]
